version:  '3'
services:
  neo4j_db:
    #image: neo4j:latest      #latest Community Edition
    image: neo4j:enterprise   #latest Enterprise Edition
    volumes:
      - ${LOCAL_WORKING_DIR}/neo4j/data:/var/lib/neo4j/data
      - ${LOCAL_WORKING_DIR}/neo4j/logs:/logs
      - ${LOCAL_WORKING_DIR}/neo4j/import:/import
      - ${LOCAL_WORKING_DIR}/neo4j/config:/var/lib/neo4j/conf
      - ${LOCAL_WORKING_DIR}/neo4j/plugins:/plugins
    ports:
      - 7474:7474    #http
      - 7473:7473    #https
      - 7687:7687    #Bolt
    environment:
      - NEO4J_AUTH=neo4j/digityser   #set password "digityser"
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=1G    #default 512MB
      - NEO4J_dbms_memory_heap_max__size=1G    #default 512MB
        #- NEO4J_dbms_security_procedures_unrestricted=algo.*   #setup plugins/
        #- NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*,algo.\\\*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
